version: "3"

services:
  fpena_test_file_manager_server:
    image: fpena_test_file_manager_server
    build: ./server
    command: ${SERVER_COMMAND:-test}
    depends_on:
      - fpena_filemanager_testdb
    restart: "no"
    volumes:
      - ./server/reports:/app/reports
      - ./server/coverage:/app/coverage
    ports:
      - 6119:8500
    environment:
      - DEV=true
      - DB_HOST=fpena_filemanager_testdb
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-pass}
  fpena_filemanager_testdb:
    image: fpena_filemanager_testdb
    build:
      context: ./db
      dockerfile: test.Dockerfile
    restart: "no"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-pass}
      - MARIADB_DATABASE=file_manager_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

