version: "3"

services:
  fpena_filemanager_server:
    image: fpena_filemanager_server
    build: ./server
    command: ${SERVER_COMMAND:-start}
    depends_on:
      - fpena_filemanager_db
    restart: "always"
    networks:
      - fpenal_filemanager_backend_network
      - fpena_filemanager_public_network
    ports:
      - 6119:8500
    environment:
      - DB_HOST=fpena_filemanager_db
      - DB_PORT=3306
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-pass}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/"]
      interval: 10s
      timeout: 30s
      retries: 10
  fpena_filemanager_db:
    image: fpena_filemanager_db
    build:
      context: db
      dockerfile: prod.Dockerfile
    restart: "always"
    networks:
      - fpenal_filemanager_backend_network
    volumes:
      - fpena_filemanager_db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-pass}
      - MARIADB_DATABASE=file_manager_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  fpena_db_adminer:
    image: adminer
    restart: always
    networks:
      - fpenal_filemanager_backend_network
    ports:
      - 6121:8080

volumes:
  fpena_filemanager_db_data:

networks:
  fpenal_filemanager_backend_network:
  fpena_filemanager_public_network:
    external: true
