version: '3'

services:
  fpenac-cicd:
    container_name: fpenac-cicd # Single container is expected
    build: .
    restart: unless-stopped
    dns:
      - 8.8.8.8
    ports:
      - "7443:8080"
      - "7444:50000"
    volumes:
      # Backup data
      - fpenac-cicd-volume:/var/jenkins_home

volumes:
  fpenac-cicd-volume:
