version: "3"

services:
  fpena_file_manager_server:
    image: fpena_file_manager_server
    build: ./file-manager-server
    command: ${SERVER_COMMAND:-start}
    depends_on:
      - fpena_preprocessing_db
    restart: "always"
    networks:
      - fpena_database_network
    ports:
      - 6119:8500
    environment:
      - DB_HOST=fpena_preprocessing_db
      - DB_PORT=3306
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-pass}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/"]
      interval: 10s
      timeout: 30s
      retries: 10
  fpena_preprocessing_db:
    image: fpena_preprocessing_db
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: "always"
    networks:
      - fpena_database_network
    volumes:
      - fpena_preprocessing_db_data_v4:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-pass}
      - MARIADB_DATABASE=file_manager_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  fpena_db_adminer:
    image: adminer
    restart: always
    networks:
      - fpena_database_network
    ports:
      - 6121:8080

volumes:
  fpena_preprocessing_db_data_v3:
  fpena_preprocessing_db_data_v4:

networks:
  fpena_database_network:
    external: true
