version: "3"

services:
  fpena_preprocessing_db:
    image: fpena_preprocessing_db
    build: .
    restart: "always"
    networks:
      - fpena_database_network
    volumes:
      - fpena_preprocessing_db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
  fpena_preprocessing_db_data:

networks:
  fpena_database_network:
    external: true
